version: '3'

services:
  build:
    image: node:12
    volumes:
      - .:/home/node/app
    working_dir: '/home/node/app'
    command: yarn build:watch
  
  postgres:
    image: postgres
    env_file: ./packages/api/.env.local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  pgadmin4:
    image: dpage/pgadmin4
    env_file: ./packages/api/.env.local
    depends_on: 
      - postgres
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: 'postgres'

  api:
    image: node:12
    env_file: ./packages/api/.env.local
    depends_on: 
      - postgres
    ports:
      - "3000:3000"
      - "9231:9231"
    volumes:
      - .:/home/node/app
    working_dir: '/home/node/app/packages/api'
    command: yarn start

  ui:
    image: node:12
    env_file: ./packages/ui/.env.local
    depends_on: 
      - api
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
    working_dir: '/home/node/app/packages/ui'
    command: yarn start

  admin-ui:
    image: node:12
    env_file: ./packages/admin-ui/.env.local
    depends_on: 
      - api
    ports:
      - "5000:5000"
    volumes:
      - .:/home/node/app
    working_dir: '/home/node/app/packages/admin-ui'
    command: yarn start